// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3PxYfXnTBLCbZvPMShdv3xBz_asnTjw',
    appId: '1:766108353885:web:86d16fa0355a7c76f2d4b4',
    messagingSenderId: '766108353885',
    projectId: 'weatherapp-d62ad',
    authDomain: 'weatherapp-d62ad.firebaseapp.com',
    storageBucket: 'weatherapp-d62ad.firebasestorage.app',
    measurementId: 'G-JSX1ETDYSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_D3mJarRqVDkNiNrC33SDJRHl8GxaWc',
    appId: '1:766108353885:android:db63520cc2b53327f2d4b4',
    messagingSenderId: '766108353885',
    projectId: 'weatherapp-d62ad',
    storageBucket: 'weatherapp-d62ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkG-8e0lMo8S0oxFAEPX0MiaZLODDaWlw',
    appId: '1:766108353885:ios:d99c9b0e9ae357cef2d4b4',
    messagingSenderId: '766108353885',
    projectId: 'weatherapp-d62ad',
    storageBucket: 'weatherapp-d62ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkG-8e0lMo8S0oxFAEPX0MiaZLODDaWlw',
    appId: '1:766108353885:ios:d99c9b0e9ae357cef2d4b4',
    messagingSenderId: '766108353885',
    projectId: 'weatherapp-d62ad',
    storageBucket: 'weatherapp-d62ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3PxYfXnTBLCbZvPMShdv3xBz_asnTjw',
    appId: '1:766108353885:web:206d3f74a39136dbf2d4b4',
    messagingSenderId: '766108353885',
    projectId: 'weatherapp-d62ad',
    authDomain: 'weatherapp-d62ad.firebaseapp.com',
    storageBucket: 'weatherapp-d62ad.firebasestorage.app',
    measurementId: 'G-7HKC1S36ML',
  );
}
